name: WebUI-FTP
on:
  push:
    branches: [ WebUI_v2.2.0 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WebUI-FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.WEBUI_FTP_SERVER }}
          user: ${{ secrets.WEBUI_FTP_USERNAME }}
          password: ${{ secrets.WEBUI_FTP_PASSWORD }}
          local_dir: "./website"
          remote_dir: "/home/webui.me/public_html"
          delete: "true"
          ftp_ssl_allow: "false"
          max_retries: "3"
