name: Windows
on:
  workflow_call:

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bundle WebUI Bridge
        run: bridge/build.ps1
      - uses: actions/cache@v3
        with:
          path: bridge/webui_bridge.h
          key: ${{ runner.os }}-${{ github.sha }}-bridge

  build:
    needs: setup
    runs-on: windows-latest
    permissions:
      contents: write
    strategy:
      matrix:
        compiler: [GCC, MSVC]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        with:
          path: bridge/webui_bridge.h
          key: ${{ runner.os }}-${{ github.sha }}-bridge
          fail-on-cache-miss: true
      - uses: microsoft/setup-msbuild@v1.1
      - if: matrix.compiler == 'MSVC'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build Debug Target
        run: |
          if ('${{ matrix.compiler }}' -eq 'MSVC') {
            nmake -f ./Makefile.nmake debug
          } else {
            mingw32-make debug
          }
      - name: Build Release Target
        run: |
          if ('${{ matrix.compiler }}' -eq 'MSVC') {
            nmake -f ./Makefile.nmake
          } else {
            mingw32-make
          }
      - name: Prepare Artifact
        shell: bash
        run: |
          cp -r include dist
          artifact=webui-${{ runner.os }}-${{ matrix.compiler }}-x64
          # Convert to lowercase (`,,` ^= lowercase shell param)
          artifact=${artifact,,}
          # Add the ARTIFACT name as GitHub environment variable.
          echo "ARTIFACT=$artifact" >> $GITHUB_ENV
          mv dist/ $artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
      - name: Prepare Release Archive
        if: github.ref_type == 'tag'
        run: 7z a -tzip $artifact.zip ${{ env.ARTIFACT }}
      - name: Release Artifact
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARTIFACT }}.zip
